schema_version = "1.0.0"

id = "ndof_viewport_switcher"
version = "1.3.4"
name = "NDOF Viewport Switcher"
tagline = "Exit fixed views (ortho/camera) with NDOF device"
maintainer = "ChrisP"
type = "add-on"

website = "https://github.com/ChrisPZone/blender-ndof-viewport-switcher"
tags = ["User Interface", "3D View"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2025-2026 ChrisP",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/.github/",
  "/*.zip",
  "/README.md"
]
